import Layout from '../components/Layout'
import { useDispatch, useSelector } from 'react-redux'
import React from 'react'
import Head from 'next/head'
import { Col, Modal, Row, Button, Input, Card, Form } from 'antd'
import Image from 'next/image'
import { Typography } from 'antd'
import Link from 'next/link'
import { registerUser } from '../src/features/auth/authSlice'

const { Title, Paragraph } = Typography

const Register = () => {
  const dispatch = useDispatch()
  const authorization = useSelector((state) => state.authentication)

  const onFinish = (values) => {
    dispatch(registerUser(values))
  }

  const onFinishFailed = (errorInfo) => {
    //console.log('Failed:', errorInfo)
  }
  return (
    <Layout
      title="Create Next App"
      description="Generated by create next app"
      headerEnabled={false}
    >
      <Head>
        <title>Whthpnd | Register</title>
        <meta name="description" content="What Happened Home Page" />
      </Head>
      <section className="">
        <div className="container">
          <Row style={{ minHeight: '100vh', alignItems: 'center' }}>
            <Col xs={24} lg={14}>
              <Image
                src="/register-illustration.svg"
                alt="Picture of the author"
                width={700}
                height={475}
              />
            </Col>
            <Col xs={24} lg={10}>
              <Card className="section-padding-1">
                <Link href="/">
                  <a>
                    <Image
                      src="/logo.svg"
                      alt="Vercel Logo"
                      width={40}
                      height={40}
                    />
                  </a>
                </Link>
                <Title level={3}>Register</Title>
                <Form
                  name="basic"
                  labelCol={{
                    span: 0
                  }}
                  wrapperCol={{
                    span: 24
                  }}
                  initialValues={{
                    remember: true
                  }}
                  onFinish={onFinish}
                  onFinishFailed={onFinishFailed}
                  autoComplete="off"
                >
                  <Form.Item
                    name="name"
                    rules={[
                      {
                        required: true,
                        message: 'Please input your username!'
                      }
                    ]}
                  >
                    <Input size="large" placeholder="Name" />
                  </Form.Item>
                  <Form.Item
                    name="email"
                    rules={[
                      {
                        required: true,
                        message: 'Please input your email!'
                      }
                    ]}
                  >
                    <Input size="large" placeholder="Email" />
                  </Form.Item>

                  <Form.Item
                    name="password"
                    rules={[
                      {
                        required: true,
                        message: 'Please input your password!'
                      }
                    ]}
                  >
                    <Input.Password size="large" placeholder="Password" />
                  </Form.Item>
                  <Form.Item
                    name="confirm"
                    dependencies={['password']}
                    hasFeedback
                    rules={[
                      {
                        required: true,
                        message: 'Please confirm your password!'
                      },
                      ({ getFieldValue }) => ({
                        validator(_, value) {
                          if (!value || getFieldValue('password') === value) {
                            return Promise.resolve()
                          }
                          return Promise.reject(
                            new Error(
                              'The two passwords that you entered do not match!'
                            )
                          )
                        }
                      })
                    ]}
                  >
                    <Input.Password size="large" placeholder="Password Again" />
                  </Form.Item>
                  <Form.Item
                    wrapperCol={{
                      span: 24
                    }}
                  >
                    <Button
                      type="primary"
                      danger
                      htmlType="submit"
                      loading={authorization.loading ? true : false}
                      className="w-100"
                      size="large"
                    >
                      Register
                    </Button>
                  </Form.Item>
                </Form>
                <p className="text-center">
                  <span className="text-muted">
                    Do you already have an account?
                  </span>
                  <Link href="/login">
                    <a>
                      <i>Log In</i>
                    </a>
                  </Link>
                </p>
              </Card>
            </Col>
          </Row>
        </div>
      </section>
    </Layout>
  )
}

export default Register
